sets.exported={
    main={ name="Claidheamh Soluis", augments={'Accuracy+11 Attack+11','"Dbl.Atk."+2','DMG:+16',}},
    sub={ name="Xiutleato", augments={'Occ. atk. twice+8','Crit.hit rate+4',}},
    ammo="Ginsen",
    head={ name="Rawhide Mask", augments={'HP+50','Accuracy+15','Evasion+20',}},
    body="Jhakri Robe +2",
    hands={ name="Herculean Gloves", augments={'Pet: Accuracy+8 Pet: Rng. Acc.+8','Pet: "Store TP"+4','Quadruple Attack +2','Accuracy+18 Attack+18','Mag. Acc.+8 "Mag.Atk.Bns."+8',}},
    legs={ name="Carmine Cuisses +1", augments={'Accuracy+20','Attack+12','"Dual Wield"+6',}},
    feet={ name="Herculean Boots", augments={'DEX+9','Pet: CHR+8','"Refresh"+1','Accuracy+17 Attack+17','Mag. Acc.+12 "Mag.Atk.Bns."+12',}},
    neck="Asperity Necklace",
    waist="Grunfeld Rope",
    left_ear="Dudgeon Earring",
    right_ear="Heartseeker Earring",
    left_ring="Apate Ring",
    right_ring="Warp Ring",
    back={ name="Rosmerta's Cape", augments={'DEX+4','Accuracy+20 Attack+20','Crit.hit rate+10',}},
}