sets.exported={
    main="Aettir",
    ammo="Ginsen",
    head={ name="Adhemar Bonnet", augments={'DEX+10','AGI+10','Accuracy+15',}},
    body="Ayanmo Corazza +1",
    hands={ name="Herculean Gloves", augments={'Attack+28','"Triple Atk."+4','DEX+10',}},
    legs={ name="Herculean Trousers", augments={'Attack+22','"Triple Atk."+4','AGI+9','Accuracy+2',}},
    feet={ name="Herculean Boots", augments={'Accuracy+23','"Triple Atk."+3','AGI+10',}},
    neck="Asperity Necklace",
    waist="Grunfeld Rope",
    left_ear="Brutal Earring",
    right_ear="Cessance Earring",
    left_ring="Prolix Ring",
    right_ring="Dim. Ring (Dem)",
    back="Atheling Mantle",
}