sets.exported={
    main={ name="Claidheamh Soluis", augments={'Accuracy+11 Attack+11','"Dbl.Atk."+2','DMG:+16',}},
    sub={ name="Usonmunku", augments={'Accuracy+10','DEX+7','DMG:+2',}},
    ammo="Ginsen",
    head={ name="Adhemar Bonnet", augments={'DEX+10','AGI+10','Accuracy+15',}},
    body="Ayanmo Corazza +1",
    hands={ name="Herculean Gloves", augments={'Attack+28','"Triple Atk."+4','DEX+10',}},
    legs={ name="Herculean Trousers", augments={'Attack+22','"Triple Atk."+4','AGI+9','Accuracy+2',}},
    feet={ name="Herculean Boots", augments={'Accuracy+23','"Triple Atk."+3','AGI+10',}},
    neck="Asperity Necklace",
    waist="Grunfeld Rope",
    left_ear="Suppanomimi",
    right_ear="Brutal Earring",
    left_ring="Apate Ring",
    right_ring="Rajas Ring",
    back={ name="Rosmerta's Cape", augments={'DEX+4','Accuracy+20 Attack+20','Crit.hit rate+10',}},
}