sets.exported={
    main={ name="Claidheamh Soluis", augments={'Accuracy+11 Attack+11','"Dbl.Atk."+2','DMG:+16',}},
    sub={ name="Xiutleato", augments={'Occ. atk. twice+8','Crit.hit rate+4',}},
    ammo="Jukukik Feather",
    head={ name="Adhemar Bonnet", augments={'DEX+10','AGI+10','Accuracy+15',}},
    body="Ayanmo Corazza +1",
    hands={ name="Herculean Gloves", augments={'Pet: Accuracy+8 Pet: Rng. Acc.+8','Pet: "Store TP"+4','Quadruple Attack +2','Accuracy+18 Attack+18','Mag. Acc.+8 "Mag.Atk.Bns."+8',}},
    legs={ name="Ta'lab Trousers", augments={'Accuracy+14','Mag. Evasion+13','Enmity-6','Crit.hit rate+3',}},
    feet="Aya. Gambieras",
    neck="Subtlety Spec.",
    waist="Fotia Belt",
    left_ear="Brutal Earring",
    right_ear="Mache Earring",
    left_ring="Apate Ring",
    right_ring="Rajas Ring",
    back={ name="Rosmerta's Cape", augments={'DEX+4','Accuracy+20 Attack+20','Crit.hit rate+10',}},
}